services:
 pb_app:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   container_name: pb_app
   env_file:
     - .env
   ports:
     - "${APP_PORT}:${APP_PORT}"
   volumes:
     - ./app:/pb_app/app
     - ./alembic:/pb_app/alembic
   depends_on:
     - postgres
   networks:
     - pb_network

 postgres:
   restart: always
   image: postgres:16.4-alpine
   container_name: pb_db
   command: postgres
   env_file:
     - .env
   ports:
     - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
   volumes:
     - ./postgres/data:/var/lib/postgresql/data
     - ./postgres/backups:/backups
   networks:
     - pb_network

networks:
  pb_network:
    driver: bridge

volumes:
  local-storage:
