"""init tables

Revision ID: 2dd476f5a3e2
Revises: 
Create Date: 2025-07-22 12:31:23.852888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd476f5a3e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('name', sa.String(), nullable=False, comment='Название роли'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('name', sa.String(), nullable=False, comment='Имя'),
    sa.Column('second_name', sa.String(), nullable=False, comment='Отчество'),
    sa.Column('surname', sa.String(), nullable=False, comment='Фамилия'),
    sa.Column('login', sa.String(), nullable=False, comment='Логин'),
    sa.Column('password', sa.String(), nullable=False, comment='Пароль'),
    sa.Column('phone', sa.String(), nullable=False, comment='Телефон'),
    sa.Column('email', sa.String(), nullable=False, comment='Электронная почта'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Роль пользователя'),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False, comment='Активен ли пользователь'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID компании'),
    sa.Column('name', sa.String(), nullable=False, comment='Название'),
    sa.Column('address', sa.String(), nullable=False, comment='Адрес'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание'),
    sa.Column('main_user_id', sa.Integer(), nullable=False, comment='ID главного пользователя'),
    sa.ForeignKeyConstraint(['main_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID компании'),
    sa.Column('name', sa.String(), nullable=False, comment='Название'),
    sa.Column('address', sa.String(), nullable=False, comment='Адрес'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='ID компании'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('masters',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID мастера'),
    sa.Column('name', sa.String(), nullable=False, comment='Имя или псевдоним мастера'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='ID компании'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='ID подразделения'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masters_id'), 'masters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_masters_id'), table_name='masters')
    op.drop_table('masters')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
